#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Account\Index.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Account/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\Manager\Views\Account\Index.cshtml"
  
    ViewBag.Title = Account.Title;
    Layout = string.Empty;



            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta http-equiv=\"content-type\" cont" +
"ent=\"text/html; charset=utf-8\"/>\r\n        <title>");


            
            #line 11 "..\..\Areas\Manager\Views\Account\Index.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link rel=\"icon\" href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                          Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\">\r\n        <link rel=\"shortcut icon\" href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                   Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\"> \r\n        <link href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Account\Index.cshtml"
               Write(Url.Content("~/Areas/Manager/Content/Css/Style.ashx"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script type=\"text/javascript\" src=" +
"\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js\"> </script>\r\n  " +
"      <script type=\"text/javascript\" src=\"");


            
            #line 16 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                       Write(Url.Content("~/Areas/Manager/Content/Js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""> </script>
        <script type=""text/javascript"">
            $(document).ready(function() {
                $("".message"").click(function() { $(this).fadeOut(""medium""); });

                if ($(""#sysMsg"").text() != """") {
                    floatBox.show(""boxMessage"");
                }

                $(""#login"").focus();
            });
        </script>
    </head>
    <body>
        <div class=""container_12"">
            <div class=""grid_4 box login"">
                <div class=""title""><small>");


            
            #line 32 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                      Write("v" + ViewBag.Version);

            
            #line default
            #line hidden
WriteLiteral("</small><h2>");


            
            #line 32 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                                                         Write(Account.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\">\r\n");


            
            #line 34 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                       Html.BeginForm("login", "account"); 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    ");


            
            #line 37 "..\..\Areas\Manager\Views\Account\Index.cshtml"
               Write(Html.Hidden("returnaction", "index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");


            
            #line 38 "..\..\Areas\Manager\Views\Account\Index.cshtml"
               Write(Html.Hidden("returncontroller", "page"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <ul class=\"form\">\r\n                        <li><label>");


            
            #line 40 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                              Write(Account.Username);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input id=\"login\" name=\"" +
"login\" type=\"text\" /></div></li>\r\n                        <li><label>");


            
            #line 42 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                              Write(Account.Password);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input name=\"password\" t" +
"ype=\"password\" /></div></li>\r\n                    </ul>\r\n                    <bu" +
"tton type=\"submit\" class=\"btn right\">");


            
            #line 45 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                                       Write(Account.Login);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 46 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                       Html.EndForm(); 

            
            #line default
            #line hidden
WriteLiteral(@"                    <div class=""clear""></div>
                </div>
            </div>
        </div>
        <div id=""boxMessage"" class=""floatbox"">
            <div class=""bg""></div>
            <div class=""box"">
                <div class=""title""><h2>");


            
            #line 54 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                  Write(Global.PopupMessageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\" style=\"min-height: 60px; text-ali" +
"gn: center; width: 360px;\">\r\n                    <p id=\"sysMsg\">");


            
            #line 56 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                              Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </body>\r\n</" +
"html>");


        }
    }
}
#pragma warning restore 1591
