#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Post
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    using Extension = Piranha.Models.Extension;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    using Post = Piranha.Resources.Post;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Post/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<Models.Manager.PostModels.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {







DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.form.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.attachment.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.media.dialog.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/Ext/jquery.equalheights.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    ");


            
            #line 12 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        var isFixed = false;\r\n        var " +
"folderId = \"\";\r\n\r\n        $(document).ready(function() {\r\n            $(\"#PostCa" +
"tegories\").chosen().change(function() {\r\n                console.log(\"change\");\r" +
"\n                var container = $(this).siblings(\".chzn-container\");\r\n\r\n       " +
"         $.each($(this).find(\"option\"), function(n, opt) {\r\n                    " +
"$(opt).removeAttr(\"selected\");\r\n                    $.each(container.find(\".resu" +
"lt-selected\"), function(i, e) {\r\n                        if ($(e).html() == $(op" +
"t).html())\r\n                            $(opt).attr(\"selected\", \"selected\");\r\n  " +
"                  });\r\n                });\r\n            });\r\n\r\n            //\r\n " +
"           // Hides the attachment editor and shows the content body.\r\n         " +
"   //\r\n            $(\"#btn_content\").click(function() {\r\n                $(\"#btn" +
"_attachments\").removeClass(\"active\");\r\n                $(\"#btn_content\").addClas" +
"s(\"active\");\r\n                $(\"#attachments\").hide();\r\n                $(\"#bod" +
"y\").show();\r\n                return false;\r\n            });\r\n\r\n            $(\'.f" +
"irst-row .box\').equalHeights();\r\n        });\r\n\r\n        //\r\n        // Hides all" +
" editors on the page. This callback is called from jquery.attachments.js\r\n      " +
"  //\r\n\r\n        function hideEditors() {\r\n            $(\"#btn_content\").removeCl" +
"ass(\"active\");\r\n            $(\"#body\").hide();\r\n        }\r\n\r\n        //\r\n       " +
" // This callback is called from jquery.attachments.js\r\n        //\r\n\r\n        fu" +
"nction addAttachment(a) {\r\n            // Store folder id so we can open the sam" +
"e folder next time.\r\n            folderId = a.ParentId;\r\n\r\n            // Add th" +
"e attachment\r\n            $(\".attachments\").append(\r\n                \'<tr data-i" +
"d=\"\' + a.Id + \'\">\' +\r\n                    \'<td><img src=\"\' + a.ThumbnailUrl + \'/" +
"50\")\" /></td>\' +\r\n                    \'<td>\' + a.Filename + \'</td>\' +\r\n         " +
"           \'<td>\' + a.Type + \'</td>\' +\r\n                    \'<td class=\"buttons " +
"three\">\' +\r\n                    \'<a class=\"icon up marg\"></a>\' +\r\n              " +
"      \'<a class=\"icon down marg\"></a>\' +\r\n                    \'<a class=\"icon de" +
"lete\"></a></td>\' +\r\n                    \'</tr>\');\r\n        }\r\n\r\n\r\n        //\r\n  " +
"      // This callback is called from jquery.attachments.js before form submit.\r" +
"\n        //\r\n\r\n        function addAttachmentData(index, val) {\r\n            $(\"" +
"#attachment_data\").append(\r\n                \'<input id=\"Post_Attachments_\' + ind" +
"ex +\r\n                    \'_\" name=\"Post.Attachments[\' + index +\r\n              " +
"      \']\" type=\"hidden\" value=\"\' + $(val).attr(\"data-id\") + \'\" />\');\r\n        }\r" +
"\n    </script>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 90 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 94 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 95 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                 if (!Model.Post.IsNew)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"http://");


            
            #line 97 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Request.Url.DnsSafeHost);

            
            #line default
            #line hidden

            
            #line 97 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                            Write(Url.GetPermalink(Model.Post.Permalink, true));

            
            #line default
            #line hidden
WriteLiteral("\" target=\"preview\" class=\"preview\">");


            
            #line 97 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                                                                             Write(Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 98 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li><a class=\"publish\">");


            
            #line 99 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                  Write(Global.ToolbarPublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 100 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                 if (Model.Post.Published > DateTime.MinValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 102 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                            Write(Url.Action("unpublish", new { id = Model.Post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"unpublish\">");


            
            #line 102 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                                    Write(Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 103 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 104 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                 if (Model.Post.Published > DateTime.MinValue && Model.Post.Updated > Model.Post.LastPublished)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 106 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                            Write(Url.Action("revert", new { id = Model.Post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"revert\">");


            
            #line 106 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                              Write(Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 107 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li><a href=\"");


            
            #line 108 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                        Write(Url.Action("delete", new { id = Model.Post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 108 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                          Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 109 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                        Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 109 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                           Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 110 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                        Write(Url.Action("edit", new { id = Model.Post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 110 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                         Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 117 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]); 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 119 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 120 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 121 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 122 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 123 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 124 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 125 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 126 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 127 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 128 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 129 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 130 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Post.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 131 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 132 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 133 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 134 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 135 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 136 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input type=\"hidden\" id=\"draft\" name=\"draft\" value=\"true\" />\r\n</div>\r\n<div " +
"class=\"first-row\">\r\n    <div class=\"grid_9\">\r\n        <div class=\"box\">\r\n       " +
"     <div class=\"title\"><h2>");


            
            #line 142 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                              Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <ul class=\"form\">\r\n" +
"                    <li>");


            
            #line 145 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Post.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 147 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Post.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 148 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Post.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li class=\"protected\">");


            
            #line 150 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Post.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 151 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                         if (!Model.Post.IsNew)
                        {
                           // <p>http://@Request.Url.DnsSafeHost@(UI.Permalink(Model.Post.Permalink))</p>
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p><i>");


            
            #line 157 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                             Write(Post.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");


            
            #line 158 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"input\">\r\n                            ");


            
            #line 160 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <a class=\"locked\"></a>\r\n                    </li>" +
"\r\n                    <li>\r\n                        ");


            
            #line 164 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Post.Excerpt));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 166 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.Post.Excerpt, new { @placeholder = Global.Optional, @rows = 3 }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 167 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Post.Excerpt));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n        <" +
"/div>\r\n    </div>\r\n    <div class=\"grid_3\">\r\n        <div class=\"box pagetemplat" +
"e\">\r\n            <div class=\"title\"><h2>");


            
            #line 175 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                              Write(Model.Template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <div class=\"edit\">\r" +
"\n                    ");


            
            #line 178 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class=""grid_12"">
        <div class=""box main-content overflow"">
            <table>
                <tr>
                    <td class=""tools"">
                        <ul>
                            <li class=""btn-content active""><a href=""#"" data-id=""pnl-content"">");


            
            #line 191 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                        Write(Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                            <li class=\"btn-settings\"><a href=\"#\" data-" +
"id=\"pnl-settings\">");


            
            #line 192 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                   Write(Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 193 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                             if (Model.Properties.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li class=\"btn-properties\"><a href=\"#\" data-id=\"p" +
"nl-properties\">");


            
            #line 195 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                           Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 196 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 197 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                             foreach (Extension ext in Model.Extensions)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a href" +
"=\"#\"");


            
            #line 200 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(ExtensionManager.GetIconPathByType(ext.Type) != string.Empty ? "style=background-image:url('" + Url.Content(ExtensionManager.GetIconPathByType(ext.Type)) + "')" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");


            
            #line 200 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                                                                                                                                                                          Write(ExtensionManager.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        ");


            
            #line 201 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(ExtensionManager.GetExtensionNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </li>" +
"\r\n");


            
            #line 204 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral(@"                        </ul>
                    </td>
                    <td>
                        <div id=""pnl-content"" class=""main content-editor"">
                            <div class=""title"">
                                <div id=""regionbuttons"" class=""buttons"">
                                    <button id=""btn_content"" class=""btn active"">");


            
            #line 211 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                           Write(Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                    <button id=\"btn_attachments\" class" +
"=\"btn\">");


            
            #line 212 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                        Write(Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2>");


            
            #line 214 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                               Write(Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div class" +
"=\"inner region-body\">\r\n                                <div id=\"body\">\r\n        " +
"                            ");


            
            #line 218 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                               Write(Html.TextAreaFor(m => m.Post.Body, new { @class = "editor", @rows = 10 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div id" +
"=\"attachments\" style=\"display: none\">\r\n                                    ");


            
            #line 221 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                        <div id=\"pnl-settings\" clas" +
"s=\"main hidden\">\r\n                            <div class=\"title\"><h2>");


            
            #line 226 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                              Write(Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div class=\"inner\">\r\n                   " +
"             <ul class=\"form\">\r\n                                    <li>\r\n      " +
"                                  <label>");


            
            #line 230 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                          Write(Global.Categories);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                        <div class=\"input\">\r\n          " +
"                                  <select name=\"PostCategories\" class=\"chzn-sele" +
"ct\" style=\"width: 190px\" multiple=\"multiple\">\r\n");


            
            #line 233 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                 foreach (SelectListItem opt in Model.Categories)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <option");


            
            #line 235 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                       Write(opt.Selected ? " selected=selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" value=\"");


            
            #line 235 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                                                   Write(opt.Value);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 235 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                                                                               Write(opt.Text);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 236 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </select></div>\r\n                    " +
"                </li>\r\n                                    <li>");


            
            #line 239 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Post.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\"> \r\n                 " +
"                           ");


            
            #line 241 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Post.Keywords, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 242 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Post.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>");


            
            #line 244 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Post.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 246 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Post.Description, new { @rows = 3, @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 247 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Post.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>\r\n                                        ");


            
            #line 250 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Post.AllowRss));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");


            
            #line 251 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Post.AllowRss));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 251 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                                               Write(Post.AllowRssDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
" </ul>\r\n                            </div>\r\n                        </div>\r\n");


            
            #line 256 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                         if (Model.Properties.Count > 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div id=\"pnl-properties\" class=\"main hidden\">\r\n      " +
"                          <div class=\"title expanded\"><h2>");


            
            #line 259 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                           Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                                <div class=\"inner optional\">\r\n      " +
"                              <ul class=\"form\">\r\n");


            
            #line 262 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                         for (int n = 0; n < Model.Properties.Count; n++)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <li>");


            
            #line 264 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 265 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 266 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 267 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 268 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 269 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 270 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 271 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                <div class=\"input\">\r\n          " +
"                                          ");


            
            #line 273 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                               Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                            </li>\r\n");


            
            #line 275 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n                                </div>" +
"\r\n                            </div>\r\n");


            
            #line 279 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        ");


            
            #line 282 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div class=\"grid_3\">\r\n");


            
            #line 290 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
     if (!Model.Post.IsNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box expandable hidden\">\r\n            <div class=\"title\"><h2>");


            
            #line 293 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                              Write(Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner optional\">\r\n                <ul class=" +
"\"list\">\r\n                    <li>");


            
            #line 296 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                                                  ");


            
            #line 297 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                              Write(Model.Post.LastPublished > DateTime.MinValue ? Model.Post.LastPublished.ToShortDateString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 298 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                                              ");


            
            #line 299 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                          Write(Model.Post.Published > DateTime.MinValue ? Model.Post.Published.ToShortDateString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 300 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 300 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                        Write(Model.Post.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 301 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                   Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 301 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
                                                        Write(Model.Post.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n");


            
            #line 305 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 307 "..\..\Areas\Manager\Views\Post\Edit.cshtml"
   Html.EndForm(); 

            
            #line default
            #line hidden

DefineSection("Foot", () => {

WriteLiteral("\r\n    <div id=\"boxContent\" class=\"floatbox\">\r\n        <div class=\"bg\"></div>\r\n   " +
"     <div class=\"box\" style=\"min-height: 260px; min-width: 510px;\">\r\n        </d" +
"iv>\r\n    </div>\r\n");


});


        }
    }
}
#pragma warning restore 1591
