#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Post
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Post = Piranha.Resources.Post;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Post/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Models.Manager.PostModels.ListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {





DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        $(document).ready(function() {
            // Set the selected template id
            $("".templates"").click(function() {
                $(""#TemplateId"").val($(this).attr(""data-templateid""));
                $(""form"").submit();
            });

            // Notification before delete
            $("".delete"").click(function() {
                return confirm(""");


            
            #line 16 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                           Write(Post.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral(@""");
            });

            // Setup post list
            var options = {
                listClass: 'list-js',
                searchId: 'search',
                valueNames: ['title', 'template', 'updated', 'created']
            };
            var postList = new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n    ");


            
            #line 30 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a onclick=\" floatBox.show(\'boxTemplates\') \" class=\"add\">");


            
            #line 34 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                        Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a class=\"refresh\">");


            
            #line 35 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                  Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\" title=\"");


            
            #line 37 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                     Write(Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 37 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                     Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n");


            
            #line 43 "..\..\Areas\Manager\Views\Post\Index.cshtml"
     using (Html.BeginForm("insert", (string)ViewContext.RouteData.Values["Controller"]))
    {
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Post\Index.cshtml"
   Write(Html.Hidden("TemplateId", "906761ea-6c04-4f4b-9365-f2c350ff4372"));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                          
        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Manager\Views\Post\Index.cshtml"
   Write(Html.Hidden("ParentId"));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Manager\Views\Post\Index.cshtml"
   Write(Html.Hidden("Seqno"));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                             

            
            #line default
            #line hidden
WriteLiteral("        <table id=\"list\" class=\"list\">\r\n            <thead>\r\n                <tr>" +
"\r\n                    <th><span class=\"sort asc\" data-sort=\"title\">");


            
            #line 51 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                            Write(Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th><span class=\"sort\" data-sort=\"template\">");


            
            #line 52 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                           Write(Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th class=\"date\"><span class=\"sort\" data-sort=\"" +
"updated\">");


            
            #line 53 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                       Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th class=\"date\"><span class=\"sort\" data-sort=\"" +
"created\">");


            
            #line 54 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                       Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th class=\"one\"></th>\r\n                </tr>\r\n " +
"           </thead>\r\n            <tbody class=\"list-js\">\r\n");


            
            #line 59 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                 foreach (Models.Post post in Model.Posts)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr");


            
            #line 61 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                   Write(post.Updated > post.LastPublished ? " class=draft" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                        <td class=\"title\"><a href=\"");


            
            #line 62 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                              Write(Url.Action("edit", new { id = post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                              ");


            
            #line 63 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                         Write(post.Title);

            
            #line default
            #line hidden

            
            #line 63 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                     Write(Html.Raw(post.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : (post.Updated > post.LastPublished ? "<span class=info-draft></span>" : string.Empty)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                          </a></td>\r\n                        <t" +
"d class=\"template\">");


            
            #line 65 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                        Write(post.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"updated\">");


            
            #line 66 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                       Write(post.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"created\">");


            
            #line 67 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                       Write(post.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"buttons\">\r\n                            " +
"<a href=\"");


            
            #line 69 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                Write(Url.Action("delete", new { id = post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Ta bort artikel\" class=\"icon delete\"></a></td>\r\n                    </tr" +
">\r\n");


            
            #line 71 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n            <tfoot>\r\n                <tr>\r\n                " +
"    <td colspan=\"5\"></td>\r\n                </tr>\r\n            </tfoot>\r\n        " +
"</table>\r\n");


            
            #line 79 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


DefineSection("Foot", () => {

WriteLiteral("\r\n    <div id=\"boxTemplates\" class=\"floatbox\">\r\n        <div class=\"bg\"></div>\r\n " +
"       <div class=\"box\">\r\n            <div class=\"title\"><a class=\"close-btn rig" +
"ht\" data-id=\"boxContent\"></a><h2>");


            
            #line 86 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                  Write(Post.PopupTypeTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n");


            
            #line 88 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                 foreach (PostTemplate template in Model.Templates)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"templates ");


            
            #line 90 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                      Write(Model.Templates.Count > 6 ? "compressed" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" left\" data-templateid=\"");


            
            #line 90 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                                                       Write(template.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <h3>");


            
            #line 91 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                       Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                        <div class=\"preview\" style=\"height: 120px; margin:" +
" 0 auto; width: 120px;\">\r\n                            ");


            
            #line 93 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                       Write(template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <p>");


            
            #line 95 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                      Write(template.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n");


            
            #line 97 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                } 

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");


});


        }
    }
}
#pragma warning restore 1591
