#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/Access.cshtml")]
    public class Access : System.Web.Mvc.WebViewPage<Models.Manager.SettingModels.AccessEditModel>
    {
        public Access()
        {
        }
        public override void Execute()
        {



DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 4 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 8 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 9 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                 if (!Model.Access.IsLocked)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                            Write(Url.Action("deleteaccess", new { id = Model.Access.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                                                      Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 12 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li><a href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                        Write(Url.Action("accesslist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 13 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                        Write(Url.Action("access", new { id = Model.Access.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 14 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                                             Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n");


            
            #line 20 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
   Html.BeginForm(); 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.HiddenFor(m => m.Access.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.HiddenFor(m => m.Access.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.HiddenFor(m => m.Access.IsLocked));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.HiddenFor(m => m.Access.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
Write(Html.HiddenFor(m => m.Access.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 30 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                          Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 34 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
               Write(Html.LabelFor(m => m.Access.Function));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n");


            
            #line 36 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                         if (!Model.Access.IsLocked)
                        {
                            
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.TextBoxFor(m => m.Access.Function));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                    
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.TextBoxFor(m => m.Access.Function, new { disabled = "disabled" }));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                                                   
                            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.HiddenFor(m => m.Access.Function));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                   
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    ");


            
            #line 46 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
               Write(Html.ValidationMessageFor(m => m.Access.Function));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 49 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
               Write(Html.LabelFor(m => m.Access.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 51 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                   Write(Html.DropDownListFor(m => m.Access.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 52 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
               Write(Html.ValidationMessageFor(m => m.Access.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 55 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
               Write(Html.LabelFor(m => m.Access.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n");


            
            #line 57 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                         if (!Model.Access.IsLocked)
                        {
                            
            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.TextAreaFor(m => m.Access.Description, new { @rows = 3, @placeholder = Global.Optional }));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                                                                           
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.TextAreaFor(m => m.Access.Description, new { @rows = 3, @disabled = "disabled", @placeholder = Global.Optional }));

            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                                                                                                   
                            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                       Write(Html.HiddenFor(m => m.Access.Description));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                                                                      
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n            </ul>\r\n        </d" +
"iv>\r\n    </div>\r\n</div>\r\n<div class=\"grid_3\">\r\n    <div class=\"box\">\r\n        <d" +
"iv class=\"title\"><h2>");


            
            #line 74 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                          Write(Settings.AccessMembers);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n");


            
            #line 76 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
             if (!Model.Access.IsNew)
            {

            
            #line default
            #line hidden
WriteLiteral("                <ul>\r\n                    <li>Todo</li>\r\n                </ul>\r\n");


            
            #line 81 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <p><em>");


            
            #line 84 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
                  Write(Settings.AccessMembersNew);

            
            #line default
            #line hidden
WriteLiteral("</em></p>\r\n");


            
            #line 85 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");


            
            #line 89 "..\..\Areas\Manager\Views\Settings\Access.cshtml"
   Html.EndForm(); 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
