#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/GroupList.cshtml")]
    public class GroupList : System.Web.Mvc.WebViewPage<Models.Manager.SettingModels.GroupListModel>
    {
        public GroupList()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
  
    ViewBag.Title = Settings.ListTitleGroups;



            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        $(document).ready(function() {
            var options = {
                listClass: 'list-js',
                searchId: 'search',
                valueNames: ['name', 'updated', 'created']
            };
            var list = new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 21 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li id=\"add\"><a href=\"");


            
            #line 25 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                 Write(Url.Action("group"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 25 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                                   Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 26 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                        Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 26 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                                  Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\"></button>");


            
            #line 28 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                       Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n   " +
"         <tr>\r\n                <th><span class=\"sort\" data-sort=\"name\">");


            
            #line 37 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                   Write(Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 38 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                                   Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 39 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                                   Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 44 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
             foreach (SysGroup group in Model.Groups)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td class=\"name");


            
            #line 47 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                               Write(group.Level > 1 ? " level" + group.Level : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 48 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                         if (User.IsMember(group.Id))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a href=\"");


            
            #line 50 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                Write(Url.Action("group", new { id = group.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 50 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                                             Write(group.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 51 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                       Write(group.Name);

            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                       
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                    <td class=\"updated\">");


            
            #line 57 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                   Write(group.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"created\">");


            
            #line 58 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                   Write(group.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"buttons\">\r\n");


            
            #line 60 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                         if (User.IsMember(group.Id))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a class=\"icon delete\" href=\"");


            
            #line 62 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                                                    Write(Url.Action("deletegroup", new { id = group.Id }));

            
            #line default
            #line hidden
WriteLiteral("\"></a>\r\n");


            
            #line 63 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");


            
            #line 66 "..\..\Areas\Manager\Views\Settings\GroupList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td colspan=" +
"\"6\"></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
