#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Settings\User.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/User.cshtml")]
    public class User : System.Web.Mvc.WebViewPage<Models.Manager.SettingModels.UserEditModel>
    {
        public User()
        {
        }
        public override void Execute()
        {



DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 4 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 8 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                        Write(Url.Action("deleteuser", new { id = Model.User.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 9 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                                                              Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                        Write(Url.Action("userlist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 10 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                              Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                        Write(Url.Action("user", new { id = Model.User.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                                                                         Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Html.BeginForm(); 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 20 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.User.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 21 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.User.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 22 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.User.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.User.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.Password.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Settings\User.cshtml"
Write(Html.HiddenFor(m => m.Password.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 28 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                          Write(Settings.UserInfo);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 32 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.User.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 34 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.User.Login));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 35 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.User.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 38 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.User.Firstname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 40 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.User.Firstname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 41 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.User.Firstname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 44 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.User.Surname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 46 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.User.Surname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 47 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.User.Surname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 50 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.User.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 52 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.TextBoxFor(m => m.User.Email));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 53 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.User.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 56 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.User.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 58 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.DropDownListFor(m => m.User.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");


            
            #line 63 "..\..\Areas\Manager\Views\Settings\User.cshtml"
     if (Model.Extensions.Count > 0)
    {
        
            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><" +
"h2>");


            
            #line 70 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                           Write(Model.User.IsNew ? Settings.CreatePassword : Settings.ChangePassword);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 74 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Password.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 76 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.PasswordFor(m => m.Password.Password));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 79 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.LabelFor(m => m.Password.PasswordConfirm));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 81 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                   Write(Html.PasswordFor(m => m.Password.PasswordConfirm));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 82 "..\..\Areas\Manager\Views\Settings\User.cshtml"
               Write(Html.ValidationMessageFor(m => m.Password.PasswordConfirm));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n            <a href=\"");


            
            #line 85 "..\..\Areas\Manager\Views\Settings\User.cshtml"
                Write(Url.Action("generatepassword", "settings", new { @id = Model.Password.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn orange hidden\">Generera lösenord</a>\r\n        </div>\r\n    </div>\r\n</" +
"div>\r\n");


            
            #line 89 "..\..\Areas\Manager\Views\Settings\User.cshtml"
   Html.EndForm(); 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
