#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/UserList.cshtml")]
    public class UserList : System.Web.Mvc.WebViewPage<Models.Manager.SettingModels.UserListModel>
    {
        public UserList()
        {
        }
        public override void Execute()
        {




DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        $(document).ready(function() {
            var options = {
                listClass: 'list-js',
                searchId: 'search',
                valueNames: ['login', 'name', 'group', 'updated', 'created']
            };
            var list = new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li id=\"add\"><a href=\"");


            
            #line 21 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                 Write(Url.Action("user"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 21 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                                  Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 22 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                        Write(Url.Action("userlist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 22 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                                 Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\"></button>");


            
            #line 24 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                       Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n " +
"           <tr>\r\n                <th></th>\r\n                <th><span class=\"sor" +
"t asc\" data-sort=\"login\">");


            
            #line 35 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                        Write(Global.Username);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"name\">");


            
            #line 36 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                   Write(Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"group\">");


            
            #line 37 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                    Write(Global.Group);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 38 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                                   Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 39 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                                   Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 44 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
             foreach (SysUser user in Model.Users)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td class=\"gravatar\">\r\n");


            
            #line 48 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                         if (!string.IsNullOrEmpty(user.Email))
                        {
                           // <img src="@UI.Gravatar.Image(user.Email, 30)" alt="Gravatar for @user.Email" />
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                    <td class=\"login\">\r\n");


            
            #line 54 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                         if (User.IsMember(user.GroupId))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a href=\"");


            
            #line 56 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                Write(Url.Action("user", new { id = user.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 56 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                                           Write(user.Login);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 57 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                       Write(user.Login);

            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                       
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>        \r\n                    <td class=\"name\">");


            
            #line 63 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                Write(user.Firstname);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 63 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                Write(user.Surname);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"group\">");


            
            #line 64 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                 Write(user.GroupName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"updated\">");


            
            #line 65 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                   Write(user.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"created\">");


            
            #line 66 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                   Write(user.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"buttons\">\r\n");


            
            #line 68 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                         if (User.IsMember(user.GroupId))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a class=\"icon delete\" href=\"");


            
            #line 70 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                                                    Write(Url.Action("deleteuser", new { id = user.Id }));

            
            #line default
            #line hidden
WriteLiteral("\"></a>\r\n");


            
            #line 71 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");


            
            #line 74 "..\..\Areas\Manager\Views\Settings\UserList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td colspan=" +
"\"6\"></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
