#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/Partial/Attachments.cshtml")]
    public class Attachments : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Attachments()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<div id=""attachment_data""></div>
<table class=""list attachments"">
    <tbody>
        <tr>
            <td class=""thumb"">
                <a id=""btn_attach"" class=""add""></a>
            </td>
            <td colspan=""4"">
                <p><i>Click to upload a new, or to choose an existing image or document.</i></p>
            </td>
        </tr>
");


            
            #line 12 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
         foreach (dynamic c in Model.AttachedContent)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr data-id=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
                    Write(c.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <td><img src=\"");


            
            #line 15 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
                         Write(Url.Content("~/thumb/" + c.Id + "/50"));

            
            #line default
            #line hidden
WriteLiteral("\" /></td>\r\n                <td>");


            
            #line 16 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
               Write(c.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");


            
            #line 17 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
               Write(c.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons three\">\r\n                    <a class=\"" +
"icon up marg\"></a>\r\n                    <a class=\"icon down marg\"></a>\r\n        " +
"            <a class=\"icon delete\"></a></td>\r\n            </tr>\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Shared\Partial\Attachments.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");


        }
    }
}
#pragma warning restore 1591
