#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml")]
    public class TinyMCE : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TinyMCE()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script type=\"text/javascript\" src=\"");


            
            #line 1 "..\..\Areas\Manager\Views\Shared\Partial\TinyMCE.cshtml"
                               Write(Url.Content("~/Areas/Manager/Content/Js/Ext/tiny_mce/tiny_mce.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""> </script>
<script type=""text/javascript"">
    tinyMCE.init({
        mode: ""specific_textareas"",
        editor_selector: ""editor"",
        theme: ""advanced"",
        plugins: ""spellchecker,paste,inlinepopups,autoresize"",
        width: ""100%"",
        height: ""340"",
        autoresize_min_height: 340,
        content_css: """);


            
            #line 11 "..\..\Areas\Manager\Views\Shared\Partial\TinyMCE.cshtml"
                 Write(Url.Content("~/Areas/Manager/Content/Css/Editor.css"));

            
            #line default
            #line hidden
WriteLiteral(@""",
        theme_advanced_buttons1: ""bold,italic,underline,|,justifyleft,justifycenter,justifyright,|,bullist,numlist,|,formatselect,removeformat,|,cut,copy,paste,pastetext,pasteword,|,link,unlink,|,spellchecker"",
        theme_advanced_buttons2: """",
        theme_advanced_buttons3: """",
        theme_advanced_toolbar_location: ""top"",
        theme_advanced_toolbar_align: ""left"",
        theme_advanced_blockformats: ""p,h2,h3,h4,h5,h6,blockquote,pre,code""
    });
</script>");


        }
    }
}
#pragma warning restore 1591
