#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
    using Piranha.WebPages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/EditorTemplates/Extension.cshtml")]
    public class Extension : System.Web.Mvc.WebViewPage<Models.Extension>
    {
        public Extension()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
  
    string folder = Model.Type.LastIndexOf('.') > -1 ? Model.Type.Substring(0, Model.Type.LastIndexOf('.')) : string.Empty;
    folder = folder != string.Empty ? folder + "/" : string.Empty;
    string view = Model.Type.Substring(folder.Length);

    Manager.MenuItem menu = Manager.GetActiveMenuItem();
    bool compat = menu != null && (menu.InternalId == "Categories" || menu.InternalId == "Media" || menu.InternalId == "Users");



            
            #line default
            #line hidden
WriteLiteral("<div id=\"pnl-");


            
            #line 13 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
        Write(ExtensionManager.GetInternalIdByType(Model.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
                                                                             Write(!compat ? "main hidden" : "box");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <div class=\"title\"><h2>");


            
            #line 14 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
                      Write(ExtensionManager.GetExtensionNameByType(Model.Type));

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n    <div class=\"inner\">\r\n        ");


            
            #line 16 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 17 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 18 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 19 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 20 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 21 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 22 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.HiddenFor(m => m.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 23 "..\..\Areas\Manager\Views\Shared\EditorTemplates\Extension.cshtml"
   Write(Html.PartialFor(folder + view, m => m.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
