#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    using Piranha.WebPages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta http-equiv=\"content-type\" cont" +
"ent=\"text/html; charset=utf-8\"/>\r\n        <title>");


            
            #line 6 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link rel=\"icon\" href=\"");


            
            #line 7 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                          Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\">\r\n        <link rel=\"shortcut icon\" href=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\"> \r\n        <link href=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(Url.Content("~/Areas/Manager/Content/Css/Ext/chosen.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <link href=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(Url.Content("~/Areas/Manager/Content/Css/Style.ashx"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script type=\"text/javascript\" src=" +
"\"");


            
            #line 11 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                       Write(Url.Content("~/Areas/Manager/Content/Js/Ext/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n        <script type=\"text/javascript\" src=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                       Write(Url.Content("~/Areas/Manager/Content/Js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n        <script type=\"text/javascript\" src=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                       Write(Url.Content("~/Areas/Manager/Content/Js/Ext/chosen.jquery.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n        <script type=\"text/javascript\">\r\n            var siteroot =" +
" \"");


            
            #line 15 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                       Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral(@""";
            siteroot += !siteroot.endsWith(""/"") ? ""/"" : """";

            $(document).ready(function() {
                $("".message"").click(function() { $(this).fadeOut(""medium""); });

                $("".chzn-select"").chosen().trigger(""liszt:updated"");
            });
        </script>
");


            
            #line 24 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
         if (!string.IsNullOrEmpty(ViewBag.Message))
        {

            
            #line default
            #line hidden
WriteLiteral("            <script type=\"text/javascript\">\r\n                setTimeout(function(" +
") {\r\n                    $(\".sys-message\").slideUp();\r\n                }, 2000);" +
"\r\n            </script>\r\n");


            
            #line 31 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        ");


            
            #line 34 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral(@"
    </head>
    <body>
        <div class=""top"">
            <div class=""container_12"">
                <div class=""grid_12 header"">
                    <a class=""home"" href=""~/""></a>
                    <a class=""public-site"" target=""preview"" href=""");


            
            #line 41 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                                             Write(WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        ");


            
            #line 42 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                   Write(WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    ");


            
            #line 43 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("Partial/Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div class=" +
"\"title\">\r\n            <div class=\"container_12\">\r\n                <div class=\"gr" +
"id_12\"><h1>");


            
            #line 49 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1></div>\r\n            </div>\r\n        </div>\r\n        <div class=\"body\">\r\n    " +
"        <div class=\"container_12\">\r\n                <div class=\"grid_12 toolbar-" +
"container\">\r\n                    ");


            
            #line 55 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(RenderSection("Toolbar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");


            
            #line 57 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                 if (!string.IsNullOrEmpty(ViewBag.Message))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"grid_12 sys-message\">\r\n                        <d" +
"iv class=\"box");


            
            #line 60 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(!string.IsNullOrEmpty(ViewBag.MessageCss) ? " " + ViewBag.MessageCss : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" \">\r\n                            <div class=\"inner\">\r\n                           " +
"     <div class=\"ico\"></div><p>");


            
            #line 62 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                                     Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            </div>\r\n                        </div>\r\n       " +
"             </div>\r\n");


            
            #line 66 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"content left\">\r\n                    ");


            
            #line 68 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>
            </div>
        </div>
        <div id=""boxSysMsg"" class=""floatbox"">
            <div class=""bg""></div>
            <div class=""box"">
                <div class=""title""><h2 id=""SysMsgTitle""></h2></div>
                <div class=""inner"">
                    <p id=""SysMsgBody""></p>
                </div>
            </div>
        </div>
        ");


            
            #line 81 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
   Write(RenderSection("Foot", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
