#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Extend.Regions
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Extensions/Piranha.Extend.Regions/HtmlRegion.cshtml")]
    public class HtmlRegion : System.Web.Mvc.WebViewPage<Extend.Regions.HtmlRegion>
    {
        public HtmlRegion()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Areas\Manager\Views\Extensions\Piranha.Extend.Regions\HtmlRegion.cshtml"
Write(Html.TextAreaFor(m => m, new { @class = "editor", @rows = 10 }));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
