#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Install
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Install\Index.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Install/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\Manager\Views\Install\Index.cshtml"
  
    ViewBag.Title = Account.InstallTitle;
    Layout = string.Empty;



            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta http-equiv=\"content-type\" cont" +
"ent=\"text/html; charset=utf-8\"/>\r\n        <title>");


            
            #line 11 "..\..\Areas\Manager\Views\Install\Index.cshtml"
          Write(Account.InstallTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link rel=\"icon\" href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                          Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\">\r\n        <link rel=\"shortcut icon\" href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                                   Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\"> \r\n        <link href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Install\Index.cshtml"
               Write(Url.Content("~/Areas/Manager/Content/Css/Style.ashx"));

            
            #line default
            #line hidden
WriteLiteral(@""" rel=""stylesheet"" type=""text/css""/>
        <script type=""text/javascript"" src=""http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js""> </script>
        <script type=""text/javascript"">
            $(document).ready(function() {
                $("".message"").click(function() { $(this).fadeOut(""medium""); });

                if ($(""#sysMsg"").text() != """") {
                    floatBox.show(""boxMessage"");
                }

                $(""#schema"").click(function() {
                    $(""#InstallType"").attr(""value"", ""SCHEMA"");
                });
            });
        </script>
    </head>
    <body>
        <div class=""container_12"">
            <div class=""grid_4 box login"">
                <div class=""title""><h2>");


            
            #line 33 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                                  Write(Account.InstallTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\">\r\n");


            
            #line 35 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                       Html.BeginForm("create", "install"); 

            
            #line default
            #line hidden
WriteLiteral("                    <ul class=\"form\">\r\n                        <li><label>");


            
            #line 37 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                              Write(Global.Username);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input name=\"UserLogin\" " +
"type=\"text\" /></div></li>\r\n                        <li><label>");


            
            #line 39 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                              Write(Global.Password);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input name=\"Password\" t" +
"ype=\"password\" /></div></li>\r\n                        <li><label>");


            
            #line 41 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                              Write(Global.Confirm);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input name=\"PasswordCon" +
"firm\" type=\"password\" /></div></li>\r\n                        <li><label>");


            
            #line 43 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                              Write(Settings.Email);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                            <div class=""input""><input name=""UserEmail"" type=""text"" /></div></li>
                        <input type=""hidden"" id=""InstallType"" name=""InstallType"" value=""FULL"" />
                        <div class=""separator""></div>
                        <br />
                        <button id=""schema"" class=""btn orange right big"">");


            
            #line 48 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                                                                    Write(Account.InstallSchema);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        <button id=\"full\" class=\"btn blue big\">");


            
            #line 49 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                                                          Write(Account.InstallSite);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </ul>\r\n");


            
            #line 51 "..\..\Areas\Manager\Views\Install\Index.cshtml"
                       Html.EndForm(); 

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"clear\"></div>\r\n                </div>\r\n          " +
"  </div>\r\n        </div>\r\n    </body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
