#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Install
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Install\Update.cshtml"
    using Piranha.Data;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Install\Update.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Install\Update.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Install/Update.cshtml")]
    public class Update : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Update()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Areas\Manager\Views\Install\Update.cshtml"
  
    ViewBag.Title = Account.UpdateTitle;
    Layout = string.Empty;

    SysParam curr = SysParam.GetByName("SITE_VERSION");



            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <meta http-equiv=\"content-type\" cont" +
"ent=\"text/html; charset=utf-8\"/>\r\n        <title>");


            
            #line 15 "..\..\Areas\Manager\Views\Install\Update.cshtml"
          Write(Account.UpdateTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n        <link rel=\"icon\" href=\"");


            
            #line 16 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                          Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\">\r\n        <link rel=\"shortcut icon\" href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                   Write(Url.Content("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\"> \r\n        <link href=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Install\Update.cshtml"
               Write(Url.Content("~/Areas/Manager/Content/Css/Style.ashx"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n        <script type=\"text/javascript\" src=" +
"\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js\"> </script>\r\n  " +
"      <script type=\"text/javascript\" src=\"");


            
            #line 20 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                       Write(Url.Content("~/Areas/Manager/Content/Js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""> </script>
        <script type=""text/javascript"">
            $(document).ready(function() {
                $("".message"").click(function() { $(this).fadeOut(""medium""); });

                if ($(""#sysMsg"").text() != """") {
                    floatBox.show(""boxMessage"");
                }
                $(""#login"").focus();
            });
        </script>
    </head>
    <body>
        <div class=""container_12"">
            <div class=""grid_4 box login"">
                <div class=""title""><h2>");


            
            #line 35 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                  Write(Account.UpdateTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\">\r\n                    <p>");


            
            #line 37 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                  Write(Html.Raw(string.Format(Account.UpdateMessage, Database.InstalledVersion, Database.CurrentVersion)));

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n                    <br />\r\n");


            
            #line 39 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                       Html.BeginForm("runupdate", "install"); 

            
            #line default
            #line hidden
WriteLiteral("                    <ul class=\"form\">\r\n                        <li><label>");


            
            #line 41 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                              Write(Account.Username);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <div class=\"input\"><input id=\"login\" name=\"" +
"login\" type=\"text\" /></div></li>\r\n                        <li><label>");


            
            #line 43 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                              Write(Account.Password);

            
            #line default
            #line hidden
WriteLiteral(@"</label>
                            <div class=""input""><input name=""password"" type=""password"" /></div></li></ul>
                    <div class=""separator""></div>
                    <br />
                    <button class=""btn full big"" type=""submit"">");


            
            #line 47 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                                          Write(Account.Update);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 48 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                       Html.EndForm(); 

            
            #line default
            #line hidden
WriteLiteral(@"                    <div class=""clear""></div>
                </div>
            </div>
        </div>
        <div id=""boxMessage"" class=""floatbox"">
            <div class=""bg""></div>
            <div class=""box"">
                <div class=""title""><h2>");


            
            #line 56 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                  Write(Global.PopupMessageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\" style=\"min-height: 60px; text-ali" +
"gn: center; width: 360px;\">\r\n                    <p id=\"sysMsg\">");


            
            #line 58 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                              Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </body>\r\n</" +
"html>");


        }
    }
}
#pragma warning restore 1591
