#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Content
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    using Piranha.Models.Manager;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Content/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<Models.Manager.ContentModels.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {





DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 6 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 10 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                        Write(Url.Action("delete", new { id = Model.Content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 11 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                             Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                        Write(Url.Action("index", new { id = Model.Content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 12 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                          Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                        Write(Url.Action("edit", new { id = Model.Content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 13 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                            Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n");


            
            #line 19 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
   Html.BeginForm("edit", "content", FormMethod.Post, new { enctype = "multipart/form-data" }); 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 22 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.IsImage));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.IsFolder));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 28 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Filename));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 30 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Width));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 31 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Height));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 32 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
Write(Html.HiddenFor(m => m.Content.Size));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n");


            
            #line 34 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
     if (!ViewBag.Folder)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 37 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                              Write(Content.ChooseFile);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <ul class=\"form\">\r\n" +
"                    <li>\r\n                        <label>");


            
            #line 41 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                          Write(Content.Upload);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div class=\"upload\">\r\n                         " +
"   <input type=\"file\" id=\"UploadedFile\" name=\"UploadedFile\" data-id=\"upload_name" +
"\" />\r\n                            <button class=\"btn blue file\" data-id=\"Uploade" +
"dFile\">");


            
            #line 44 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                            Write(Global.ChooseFile);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                            <div class=""input"">
                                <input id=""upload_name"" type=""text"" />
                            </div>
                        </div>
                    </li>
                    <li>
                        ");


            
            #line 51 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.FileUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 53 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.FileUrl, new { @placeholder = Global.FileUrl }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n   " +
"     </div>\r\n");


            
            #line 58 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 60 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                          Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 64 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
               Write(Html.LabelFor(m => m.Content.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 66 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Content.Name, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 69 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
               Write(Html.LabelFor(m => m.Content.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        <select id=\"Co" +
"ntent_ParentId\" name=\"Content.ParentId\">\r\n");


            
            #line 72 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                             foreach (Placement f in Model.Folders)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <option value=\"");


            
            #line 74 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                          Write(f.Value);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 74 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                    Write(f.Value == Model.Content.ParentId ? " selected=selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                    ");


            
            #line 75 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                               Write(Html.Raw(f.Text));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 76 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </select>\r\n                    </div>\r\n                </" +
"li>\r\n");


            
            #line 80 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                 if (!ViewBag.Folder)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        ");


            
            #line 83 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Content.AlternateText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 85 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Content.AlternateText, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </li>\r\n");



WriteLiteral("                    <li>\r\n                        ");


            
            #line 88 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Content.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 90 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.Content.Description, new { @rows = 3, @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </li>\r\n");


            
            #line 92 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n    </div>\r\n");


            
            #line 96 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
     if (Model.Extensions.Count > 0)
    {
        
            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden

            
            #line 100 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
     if (!Model.Content.IsNew && !Model.Content.IsFolder)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 103 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                              Write(Content.FileInformation);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <ul class=\"form\">\r\n" +
"                    <li>");


            
            #line 106 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Content.Filename));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <p>");


            
            #line 107 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                      Write(Model.Content.Filename);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </li>\r\n                    <li>");


            
            #line 109 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Content.Size));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <p>");


            
            #line 110 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                      Write(Math.Max(Model.Content.Size / 1024, 1));

            
            #line default
            #line hidden
WriteLiteral(" kb (");


            
            #line 110 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                   Write(Model.Content.GetTotalSize() / 1024);

            
            #line default
            #line hidden
WriteLiteral(" kb ");


            
            #line 110 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                                            Write(Content.IncludingCache);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                    </li>\r\n                    <li>");


            
            #line 112 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Content.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <p>");


            
            #line 113 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                      Write(Model.Content.Type);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </li>\r\n");


            
            #line 115 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                     if (Model.Content.IsImage)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><label>");


            
            #line 117 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                              Write(Content.ImageSize);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <p>");


            
            #line 118 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                          Write(Model.Content.Width);

            
            #line default
            #line hidden

            
            #line 118 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                               Write(Model.Content.Height);

            
            #line default
            #line hidden
WriteLiteral(" px</p>\r\n                        </li>\r\n");


            
            #line 120 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <li><label>");


            
            #line 121 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                          Write(Global.PublicLink);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n  ");



WriteLiteral("\r\n                    </li>\r\n                </ul>\r\n            </div>\r\n        <" +
"/div>\r\n");


            
            #line 127 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"grid_3\">\r\n");


            
            #line 130 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
     if (Model.Content.IsImage)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 133 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                              Write(Global.Thumbnail);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n");


            
            #line 135 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                 if (!Model.Content.IsNew)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <img style=\"max-width: 190px\" alt=\"");


            
            #line 137 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                  Write(Model.Content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 137 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                     Write(Url.Content("~/thumb/" + Model.Content.Id + "/190"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 138 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p><em>");


            
            #line 141 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                      Write(Content.ThumbnailNewDescription);

            
            #line default
            #line hidden
WriteLiteral("</em></p>\r\n");


            
            #line 142 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");


            
            #line 145 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box pagetemplate overflow\">\r\n        <div class=\"title\"><h2>");


            
            #line 147 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                          Write(Global.Categories);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <select name=\"ContentCatego" +
"ries\" class=\"chzn-select\" style=\"width: 190px\" multiple=\"multiple\">\r\n");


            
            #line 150 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                 foreach (SelectListItem opt in Model.Categories)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <option");


            
            #line 152 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                       Write(opt.Selected ? " selected=selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" value=\"");


            
            #line 152 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                   Write(opt.Value);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 152 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                                                                                               Write(opt.Text);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 153 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n        </div>\r\n    </div>\r\n</div>\r\n");


            
            #line 158 "..\..\Areas\Manager\Views\Content\Edit.cshtml"
   Html.EndForm(); 

            
            #line default
            #line hidden

DefineSection("Foot", () => {

WriteLiteral(@"
    <div id=""boxUploads"" class=""floatbox"">
        <div class=""bg""></div>
        <div class=""box"" style=""min-height: 260px; min-width: 510px;"">
            <div class=""title""><h2>Uploaded files</h2></div>
            <div class=""inner"">
            </div>
        </div>
    </div>
");


});


        }
    }
}
#pragma warning restore 1591
