#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Content
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Content\Index.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Content/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Models.Manager.ContentModels.ListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Content\Index.cshtml"
  
    ViewBag.Title = Content.ListTitle;



            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        function formatSitemap() {
            $.each($("".sitemap li:visible""), function(i, e) {
                if (i % 2 == 1)
                    $(this).addClass(""odd"");
                else $(this).removeClass(""odd"");
            });
        }

        $(document).ready(function() {
            formatSitemap();

            // Handle the site tree
            $("".sitemap .action"").click(function() {
                var li = $(this).parent().parent();
                li.toggleClass(""collapsed"");
                li.toggleClass(""expanded"");
                formatSitemap();
            });
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n    ");


            
            #line 31 "..\..\Areas\Manager\Views\Content\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a href=\"");


            
            #line 35 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                        Write(Url.Action("insert"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 35 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                                                           Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 36 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                        Write(Url.Action("insertfolder"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"addfolder\">");


            
            #line 36 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                                                                       Write(Content.ToolbarAddFolder);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 37 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                        Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 37 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                                                              Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\" title=\"");


            
            #line 39 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                                     Write(Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 39 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                                                                     Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <ul class=\"sitemap media\">\r\n        <li class=\"heade" +
"r\">\r\n            <span class=\"buttons\"></span>\r\n            <span class=\"date\">");


            
            #line 48 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                          Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <span class=\"date\">");


            
            #line 49 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                          Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <span class=\"title\">");


            
            #line 50 "..\..\Areas\Manager\Views\Content\Index.cshtml"
                           Write(Content.Filename);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </li>\r\n        ");


            
            #line 52 "..\..\Areas\Manager\Views\Content\Index.cshtml"
   Write(Html.Partial("Partial/ContentTree", Model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </ul>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
