#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Extension = Piranha.Models.Extension;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Models.Manager.PageModels;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {







DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.form.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.regions.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.attachment.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.media.dialog.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/Ext/jquery.equalheights.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    ");


            
            #line 13 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral(@"
    <script type=""text/javascript"">
        var folderId = """";

        $(document).ready(function() {
            $(""#Page_Title"").focus();

            $(""#Page_ParentId"").change(function() {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();

                $.get(""");


            
            #line 26 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid, function(data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");


            
            #line 35 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral("?page_id=\" + page_id + \"&group_id=\" + group_id, function(data) {\r\n               " +
"     $(\"#disable-groups\").html(data);\r\n                });\r\n            });\r\n\r\n " +
"           $(\'#btnMove\').click(function() {\r\n                $(\'#placement-edit\'" +
").slideToggle(\'fast\');\r\n                $(this).toggleClass(\'active\');\r\n        " +
"        return false;\r\n            });\r\n\r\n            $(\'.first-row .box\').equal" +
"Heights();\r\n        });\r\n\r\n        //\r\n        // Hides all editors on the page." +
" This callback is called from jquery.attachments.js\r\n        //\r\n\r\n        funct" +
"ion hideEditors() {\r\n            $(\"#pageregions .input, #globalregions .input\")" +
".hide();\r\n            $(\"#regionbuttons button\").removeClass(\"active\");\r\n       " +
"     $(\"#attachments\").hide();\r\n\r\n            $(\"#regions .region-body\").hide();" +
"\r\n            $(\"#regionbuttons button\").removeClass(\"active\");\r\n            $(\"" +
"#attachments\").hide();\r\n        }\r\n\r\n        //\r\n        // This callback is cal" +
"led from jquery.attachments.js\r\n        //\r\n\r\n        function addAttachment(a) " +
"{\r\n            // Store folder id so we can open the same folder next time.\r\n   " +
"         folderId = a.ParentId;\r\n\r\n            // Add the attachment\r\n          " +
"  $(\".attachments\").append(\r\n                \'<tr data-id=\"\' + a.Id + \'\">\' +\r\n  " +
"                  \'<td><img src=\"\' + a.ThumbnailUrl + \'/50\")\" /></td>\' +\r\n      " +
"              \'<td>\' + a.DisplayName + \'</td>\' +\r\n                    \'<td>\' + a" +
".Type + \'</td>\' +\r\n                    \'<td class=\"buttons three\">\' +\r\n         " +
"           \'<a class=\"icon up marg\"></a>\' +\r\n                    \'<a class=\"icon" +
" down marg\"></a>\' +\r\n                    \'<a class=\"icon delete\"></a></td>\' +\r\n " +
"                   \'</tr>\');\r\n        }\r\n\r\n        //\r\n        // This callback " +
"is called from jquery.attachments.js before form submit.\r\n        //\r\n\r\n        " +
"function addAttachmentData(index, val) {\r\n            $(\"#attachment_data\").appe" +
"nd(\r\n                \'<input id=\"Page_Attachments_\' + index +\r\n                 " +
"   \'_\" name=\"Page.Attachments[\' + index +\r\n                    \']\" type=\"hidden\"" +
" value=\"\' + $(val).attr(\"data-id\") + \'\" />\');\r\n        }\r\n    </script>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 98 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 102 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 103 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.Page.IsNew)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"http://");


            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Request.Url.DnsSafeHost);

            
            #line default
            #line hidden

            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                            Write(Url.GetPermalink(Model.Page.Permalink, true));

            
            #line default
            #line hidden
WriteLiteral("\" target=\"preview\" class=\"preview\">");


            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 106 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li><a class=\"publish\">");


            
            #line 107 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(Global.ToolbarPublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 108 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (Model.Page.Published > DateTime.MinValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Url.Action("unpublish", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"unpublish\">");


            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                    Write(Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 112 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Url.Action("revert", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"revert\">");


            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                              Write(Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.Page.IsNew && Model.CanDelete)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a href=\"");


            
            #line 118 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Url.Action("delete", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 118 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                              Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 119 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li><a href=\"");


            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        Write(Url.Action("index", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                       Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        Write(Url.Action("edit", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                         Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]); 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 131 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 132 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 133 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 134 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 135 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 136 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 137 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 139 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 140 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 142 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 143 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 144 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 145 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 146 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 147 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 148 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input type=\"hidden\" id=\"draft\" name=\"draft\" value=\"true\" />\r\n    <input ty" +
"pe=\"hidden\" id=\"org_parentid\" value=\"");


            
            #line 150 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             Write(Model.Page.ParentId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</div>\r\n<div class=\"first-row\">\r\n    <div class=\"grid_9\">\r\n        <div cla" +
"ss=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 155 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <ul class=\"form\">\r\n" +
"                    <li>");


            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 161 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>");


            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 165 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li class=\"protected\">");


            
            #line 168 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 169 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Permalink != null && !string.IsNullOrEmpty(Model.Permalink.Name))
                        {
                            //<p>http://@Request.Url.DnsSafeHost@(UI.Permalink(Model.Permalink.Name))</p>
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p><i>");


            
            #line 175 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");


            
            #line 176 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"input\">\r\n                            ");


            
            #line 178 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 179 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a class=\"locked\"></a>\r\n                    </li>\r\n    " +
"                <li>\r\n                        <label>");


            
            #line 183 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button class=\"btn right\" id=\"btnMove\">Move</bu" +
"tton>\r\n");


            
            #line 185 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.Page.IsStartpage)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>");


            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");


            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                         Write(Model.Page.Seqno > 1 ? Global.PlacementAfter : Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");


            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                               Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");


            
            #line 188 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>");


            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 192 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div id=\"placement-edit\" style=\"display: none\">\r\n        " +
"                    ");


            
            #line 194 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\">\r\n                              " +
"  <select id=\"Page_ParentId\" name=\"Page.ParentId\">\r\n");


            
            #line 197 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (EditModel.PagePlacement p in Model.Parents)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <option value=\"");


            
            #line 199 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(p.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 199 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                         Write(p.IsSelected ? " selected=selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                            ");


            
            #line 200 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 201 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                          ");


            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\" id=\"div-seqno\">\r\n               " +
"                 <select id=\"Page_Seqno\" name=\"Page.Seqno\">\r\n");


            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (EditModel.PagePlacement s in Model.Siblings)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <option value=\"");


            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(s.Seqno);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                            Write(s.IsSelected ? " selected=selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                 Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 210 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral(@"                                </select>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class=""grid_3"">
        <div class=""box pagetemplate"">
            <div class=""title""><h2>");


            
            #line 221 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Model.Template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <div class=\"edit\">\r" +
"\n                    ");


            
            #line 224 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class=""grid_12"">
        <div class=""box main-content"">
            <table>
                <tr>
                    <td class=""tools"">
                        <ul>
                            <li class=""btn-content active""><a href=""#"" data-id=""pnl-content"">");


            
            #line 237 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                        Write(Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                            <li class=\"btn-settings\"><a href=\"#\" data-" +
"id=\"pnl-settings\">");


            
            #line 238 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                   Write(Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 239 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.Properties.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li class=\"btn-properties\"><a href=\"#\" data-id=\"p" +
"nl-properties\">");


            
            #line 241 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                           Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 242 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 243 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             foreach (Extension ext in Model.Extensions)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a href" +
"=\"#\"");


            
            #line 246 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(ExtensionManager.GetIconPathByType(ext.Type) != string.Empty ? "style=background-image:url('" + Url.Content(ExtensionManager.GetIconPathByType(ext.Type)) + "')" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");


            
            #line 246 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                                                                                          Write(ExtensionManager.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        ");


            
            #line 247 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(ExtensionManager.GetExtensionNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n                                </li>" +
"\r\n");


            
            #line 250 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral(@"                        </ul>
                    </td>
                    <td>
                        <div id=""pnl-content"" class=""main content-editor"">
                            <div class=""title"">
                                <div id=""regionbuttons"" class=""buttons"">
");


            
            #line 257 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     for (int n = 0; n < Model.Regions.Count; n++)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <button id=\"");


            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               Write(Html.Raw("btn_" + Model.Regions[n].InternalId));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn");


            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                           Write(n > 0 ? string.Empty : " active");

            
            #line default
            #line hidden
WriteLiteral(" region\">");


            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                      Write(Model.Regions[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 260 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <button id=\"btn_attachments\" class=\"btn");


            
            #line 261 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Regions.Count == 0 ? " active" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 261 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                              Write(Piranha.Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2 id=\"section-title\">");


            
            #line 263 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div class" +
"=\"inner\">\r\n");


            
            #line 266 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 if (Model.Regions.Count > 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div id=\"regions\">\r\n                         " +
"               ");


            
            #line 269 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n");


            
            #line 271 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <div id=\"attachments\" ");


            
            #line 272 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Model.Regions.Count > 0 ? "style=display:none" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                    ");


            
            #line 273 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                        <div id=\"pnl-settings\" clas" +
"s=\"main hidden\">\r\n                            <div class=\"title\"><h2>");


            
            #line 278 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div class=\"inner\">\r\n                   " +
"             <ul class=\"form\">\r\n                                    <li>\r\n      " +
"                                  ");


            
            #line 282 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 284 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.DropDownListFor(m => m.Page.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 285 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.DisabledGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div id=\"disable-groups\" class=\"block\">" +
"\r\n");


            
            #line 287 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               List<SelectListItem> dGroups = Model.Groups.Where(g => g.Value != Guid.Empty.ToString()).ToList(); 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                            ");


            
            #line 290 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Partial("Partial/GroupList", new GroupListModel { Groups = Model.DisableGroups, Page = Model.Page }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </li>\r\n                                    <li>\r\n                          " +
"              ");


            
            #line 294 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");


            
            #line 295 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 295 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
"     <li>");


            
            #line 297 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\"> \r\n                 " +
"                           ");


            
            #line 299 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.Keywords, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 300 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>");


            
            #line 302 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 304 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Page.Description, new { @rows = 3, @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 305 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");


            
            #line 307 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowController)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>");


            
            #line 309 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.LabelFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <div class=\"input\">\r\n              " +
"                                  ");


            
            #line 311 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !string.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral(" </div>\r\n                                            ");


            
            #line 312 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </li>\r\n");


            
            #line 314 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden

            
            #line 315 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowRedirect)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>");


            
            #line 317 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <div class=\"input\">\r\n              " +
"                                  ");


            
            #line 319 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !string.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral(" </div>\r\n                                            ");


            
            #line 320 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </li>\r\n");


            
            #line 322 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");


            
            #line 326 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Properties.Count > 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div id=\"pnl-properties\" class=\"main hidden\">\r\n      " +
"                          <div class=\"title\"><h2>");


            
            #line 329 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                                <div class=\"inner\">\r\n               " +
"                     <ul class=\"form\">\r\n");


            
            #line 332 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         for (int n = 0; n < Model.Properties.Count; n++)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <li>");


            
            #line 334 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 335 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 336 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 337 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 338 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 340 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                ");


            
            #line 341 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                           Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                <div class=\"input\">\r\n          " +
"                                          ");


            
            #line 343 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                            </li>\r\n");


            
            #line 345 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n                                </div>" +
"\r\n                            </div>\r\n");


            
            #line 349 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        ");


            
            #line 352 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div class=\"grid_3 hidden\">\r\n");


            
            #line 360 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Model.Page.IsNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box expandable\">\r\n            <div class=\"title\"><h2>");


            
            #line 363 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner optional\">\r\n                <ul class=" +
"\"list\">\r\n                    <li>");


            
            #line 366 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                                                  ");


            
            #line 367 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Model.Page.LastPublished > DateTime.MinValue ? Model.Page.LastPublished.ToShortDateString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 368 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                                              ");


            
            #line 369 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          Write(Model.Page.Published > DateTime.MinValue ? Model.Page.Published.ToShortDateString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 370 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 370 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                        Write(Model.Page.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                    <li>");


            
            #line 371 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 371 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                        Write(Model.Page.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n");


            
            #line 375 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 377 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.EndForm(); 

            
            #line default
            #line hidden

DefineSection("Foot", () => {

WriteLiteral("\r\n    <div id=\"boxContent\" class=\"floatbox\">\r\n        <div class=\"bg\"></div>\r\n   " +
"     <div class=\"box\" style=\"min-height: 260px; min-width: 510px;\">\r\n        </d" +
"iv>\r\n    </div>\r\n");


            
            #line 384 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (false)
    {
        // (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("        <script type=\"text/javascript\">\r\n            $(document).ready(function()" +
" {\r\n                $(\".toolbar .page-preview\").attr(\"src\", \"http://");


            
            #line 389 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                           Write(Request.Url.DnsSafeHost);

            
            #line default
            #line hidden

            
            #line 389 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                    Write(Url.GetPreviewlink(Model.Page.Id).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\");\r\n                $.each($(\".toolbar .tooltip\"), function(i, e) {\r\n           " +
"         $(this).css({ left: -(($(this).outerWidth() - $(this).parent(\"li\").widt" +
"h()) / 2) });\r\n                });\r\n            });\r\n        </script>\r\n");


            
            #line 395 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden

});


        }
    }
}
#pragma warning restore 1591
