#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.ListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {




DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        //
        // Sets all hidden fields before submit
        function preSubmit(parentid, seqno) {
            $(""#ParentId"").val(parentid);
            $(""#Seqno"").val(seqno);

            floatBox.show('boxTemplates');

            return false;
        }

        var deletemsg = """);


            
            #line 17 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Piranha.Resources.Page.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        function formatSitemap() {\r\n            $.each($(\".sitemap li:visib" +
"le\"), function(i, e) {\r\n                if (i % 2 == 1)\r\n                    $(t" +
"his).addClass(\"odd\");\r\n                else $(this).removeClass(\"odd\");\r\n       " +
"     });\r\n        }\r\n\r\n        var currmove;\r\n\r\n        $(document).ready(functi" +
"on() {\r\n            formatSitemap();\r\n\r\n            // Handle the site tree\r\n   " +
"         $(\".sitemap .action\").click(function() {\r\n                var li = $(th" +
"is).parent().parent();\r\n                li.toggleClass(\"collapsed\");\r\n          " +
"      li.toggleClass(\"expanded\");\r\n                formatSitemap();\r\n           " +
" });\r\n\r\n            // Set the selected template id\r\n            $(\".templates\")" +
".click(function() {\r\n                $(\"#TemplateId\").val($(this).attr(\"data-tem" +
"plateid\"));\r\n                $(\"form\").submit();\r\n            });\r\n\r\n           " +
" $(\".delete\").click(function() {\r\n                return confirm(deletemsg);\r\n  " +
"          });\r\n\r\n            // Setup page list\r\n            var options = {\r\n  " +
"              listClass: \'list-js\',\r\n                searchId: \'search\',\r\n      " +
"          valueNames: [\'title\', \'template\', \'updated\', \'created\']\r\n            }" +
";\r\n            var pageList = new List(\'list\', options);\r\n\r\n            // Switc" +
"h between list/tree\r\n            $(\"#search\").keyup(function() {\r\n              " +
"  if ($(this).val() != \"\") {\r\n                    $(\".sitemap\").hide();\r\n       " +
"             $(\".list\").show();\r\n                } else {\r\n                    $" +
"(\".list\").hide();\r\n                    $(\".sitemap\").show();\r\n                }\r" +
"\n            });\r\n        });\r\n\r\n        function bindMove() {\r\n            $(\"." +
"move .title a\").click(function() {\r\n                if ($(this).parent().parent(" +
").hasClass(\"expanded\"))\r\n                    alert(\"move: \" + currmove + \" below" +
": \" + $(this).parent().parent().attr(\"id\"));\r\n                else alert(\"move: " +
"\" + currmove + \" after: \" + $(this).parent().parent().attr(\"id\"));\r\n\r\n          " +
"      return false;\r\n            });\r\n        }\r\n    </script>\r\n    <!-- Restyle" +
" the list a bit to match tree -->\r\n    <style type=\"text/css\">\r\n        table.li" +
"st th:first-child,\r\n        table.list tbody td:first-child > * { padding-left: " +
"30px; }\r\n    </style>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n    ");


            
            #line 87 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a onclick=\" floatBox.show(\'boxTemplates\') \" class=\"add\">");


            
            #line 91 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                        Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 92 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                        Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 92 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                              Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\" title=\"");


            
            #line 94 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                     Write(Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 94 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                     Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n");


            
            #line 100 "..\..\Areas\Manager\Views\Page\Index.cshtml"
     using (Html.BeginForm("insert", (string)ViewContext.RouteData.Values["Controller"]))
    {
        
            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\Manager\Views\Page\Index.cshtml"
   Write(Html.Hidden("TemplateId", "906761ea-6c04-4f4b-9365-f2c350ff4372"));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                          
        
            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\Manager\Views\Page\Index.cshtml"
   Write(Html.Hidden("ParentId"));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\Manager\Views\Page\Index.cshtml"
   Write(Html.Hidden("Seqno"));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                             


            
            #line default
            #line hidden
WriteLiteral("        <ul class=\"sitemap\">\r\n            <li class=\"header\">\r\n                <s" +
"pan class=\"buttons\"></span>\r\n                <span class=\"date\">");


            
            #line 109 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span class=\"date\">");


            
            #line 110 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span class=\"type\">");


            
            #line 111 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              Write(Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span class=\"title\">");


            
            #line 112 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                               Write(Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </li>\r\n            ");


            
            #line 114 "..\..\Areas\Manager\Views\Page\Index.cshtml"
       Write(Html.Partial(@"~/Areas/Manager/Views/Page/Partial/SiteTree.cshtml", Model.SiteMap));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n");


            
            #line 116 "..\..\Areas\Manager\Views\Page\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <table id=\"list\" class=\"list\" style=\"display: none\">\r\n            <thead>" +
"\r\n                <tr>\r\n                    <th><span class=\"sort asc\" data-sort" +
"=\"title\">");


            
            #line 120 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                            Write(Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th style=\"width: 200px\"><span class=\"sort\" dat" +
"a-sort=\"template\">");


            
            #line 121 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                Write(Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th class=\"date\"><span class=\"sort\" data-sort=\"" +
"updated\">");


            
            #line 122 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                       Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th class=\"date\"><span class=\"sort\" data-sort=\"" +
"created\">");


            
            #line 123 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                       Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                    <th></th>\r\n                </tr>\r\n            <" +
"/thead>\r\n            <tbody class=\"list-js\">\r\n");


            
            #line 128 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                 foreach (Sitemap page in Model.Pages)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                   Write(page.Updated > page.LastPublished ? " class=draft" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">\r\n                        <td class=\"title\"><a href=\"");


            
            #line 131 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                              Write(Url.Action("edit", new { id = page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                              ");


            
            #line 132 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                         Write(page.Title);

            
            #line default
            #line hidden

            
            #line 132 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                     Write(Html.Raw(page.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : (page.Updated > page.LastPublished ? "<span class=info-draft></span>" : string.Empty)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                          </a></td>\r\n                        <t" +
"d class=\"template\">");


            
            #line 134 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                        Write(page.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"updated\">");


            
            #line 135 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                       Write(page.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"created\">");


            
            #line 136 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                       Write(page.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"buttons three\">\r\n                      " +
"      <button class=\"icon add-after marg\" title=\"");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                  Write(Piranha.Resources.Page.ListAddAfter);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\" return preSubmit(\'");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                    Write(page.ParentId);

            
            #line default
            #line hidden
WriteLiteral("\', ");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                                      Write(page.Seqno + 1);

            
            #line default
            #line hidden
WriteLiteral(") \" type=\"submit\"></button>\r\n                            <button class=\"icon add-" +
"below marg\" title=\"");


            
            #line 139 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                  Write(Piranha.Resources.Page.ListAddBelow);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\" return preSubmit(\'");


            
            #line 139 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                    Write(page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', 1) \" type=\"submit\"></button>\r\n");


            
            #line 140 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                             if (page.Pages.Count == 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a href=\"");


            
            #line 142 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                    Write(Url.Action("delete", "page", new { id = page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 142 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                Write(Piranha.Resources.Page.ListDelete);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"icon delete\"></a>\r\n");


            
            #line 143 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                    </tr>\r\n");


            
            #line 146 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n            <tfoot>\r\n                <tr>\r\n                " +
"    <td colspan=\"5\"></td>\r\n                </tr>\r\n            </tfoot>\r\n        " +
"</table>\r\n");


            
            #line 154 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


DefineSection("Foot", () => {

WriteLiteral("\r\n    <div id=\"boxTemplates\" class=\"floatbox\">\r\n        <div class=\"bg\"></div>\r\n " +
"       <div class=\"box\">\r\n            <div class=\"title\"><a class=\"close-btn rig" +
"ht\" data-id=\"boxContent\"></a><h2>");


            
            #line 161 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                  Write(Piranha.Resources.Page.PopupTypeTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n");


            
            #line 163 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                 foreach (PageTemplate template in Model.Templates)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"templates ");


            
            #line 165 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                      Write(Model.Templates.Count > 6 ? "compressed" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" left\" data-templateid=\"");


            
            #line 165 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                       Write(template.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <h3>");


            
            #line 166 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                       Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                        <div class=\"preview\">\r\n                           " +
" ");


            
            #line 168 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                       Write(template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <p>");


            
            #line 170 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                      Write(template.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n");


            
            #line 172 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"clear\"></div>\r\n            </div>\r\n        </div>\r\n  " +
"  </div>\r\n");


});


        }
    }
}
#pragma warning restore 1591
