#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Template
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Template/PageEdit.cshtml")]
    public class PageEdit : System.Web.Mvc.WebViewPage<Models.Manager.TemplateModels.PageEditModel>
    {
        public PageEdit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
  
    ViewBag.Selected = "Settings";
    ViewBag.SelectedTab = "PageType";



            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.template.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.regiontemplate.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/Ext/json2.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n    <script type=\"text/javascript\">\r\n        /**\r\n         * This v" +
"ar is needed by the regiontemplate script.\r\n         */\r\n        var templateid " +
"= \'");


            
            #line 16 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                     Write(Model.Template.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 20 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 24 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 25 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                        Write(Url.Action("deletepage", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\" title=\"\">");


            
            #line 25 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                                                           Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 26 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                        Write(Url.Action("pagelist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 26 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                              Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 27 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                        Write(Url.Action("page", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 27 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                                             Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 34 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
   Html.BeginForm("page", "template"); 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 36 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 37 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 38 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 39 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 40 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 41 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div class=\"grid_9\">\r\n    <div class=\"box expandable\">\r\n        <div cl" +
"ass=\"title\"><h2>");


            
            #line 45 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 48 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 50 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 51 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>");


            
            #line 53 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 55 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Description, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n            <ul class=\"form opt" +
"ional\">               \r\n                <li>");


            
            #line 59 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Preview));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 61 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Preview, new { @rows = 8 }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>                \r\n            </ul>\r\n        </div>\r" +
"\n    </div>\r\n    <div class=\"box content-editor\">\r\n        <div class=\"title\"><h" +
"2>");


            
            #line 67 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Global.Regions);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <table class=\"list region-e" +
"ditor\">\r\n                <tbody>\r\n                    <tr>\r\n                    " +
"    <th>");


            
            #line 72 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");


            
            #line 73 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Global.InternalId);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");


            
            #line 74 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th></th>\r\n                    </tr>\r\n            " +
"        ");


            
            #line 77 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral(@"
                    <tr class=""dark"">
                        <td class=""form"">
                            <div class=""input"">
                                <input type=""text"" id=""newregionName"" /></div>
                        </td>
                        <td class=""form"">
                            <div class=""input"">
                                <input type=""text"" id=""newregionInternalId"" /></div>
                        </td>
                        <td class=""form"">
                            <div class=""input"">
                                ");


            
            #line 89 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                           Write(Html.DropDownList("newregionType", new SelectList(Model.RegionTypes, "Type", "Name")));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </td>\r\n                        <td class=\"buttons" +
" four\">\r\n                            <button id=\"btnAddRegion\" class=\"btn marg-b" +
"ig\">");


            
            #line 92 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                      Write(Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </td>\r\n                    </tr>\r\n            " +
"    </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n    <div class=\"" +
"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 100 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Global.Advanced);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 103 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Controller));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"right\">\r\n                        ");


            
            #line 105 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.CheckBoxFor(m => m.Template.ShowController));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"input short\">\r\n                        ");


            
            #line 107 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Controller, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>");


            
            #line 109 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Redirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"right\">\r\n                        ");


            
            #line 111 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.CheckBoxFor(m => m.Template.ShowRedirect));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"input short\">\r\n                        ");


            
            #line 113 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Redirect, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n<div class=\"grid_3\">\r\n");


            
            #line 120 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
     if (!Model.Template.IsNew && !string.IsNullOrEmpty(Model.Template.Preview.ToHtmlString()))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box pagetemplate\">\r\n            <div class=\"title\"><h2>");


            
            #line 123 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                              Write(Resources.Page.HtmlPreview);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <div class=\"edit\">\r" +
"\n                    ");


            
            #line 126 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");


            
            #line 130 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 132 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div id=\"region_data\"></div" +
">\r\n            <ul id=\"properties\" class=\"list buttons\">\r\n");


            
            #line 136 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                 foreach (string property in Model.Template.Properties)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><span>");


            
            #line 138 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                         Write(property);

            
            #line default
            #line hidden
WriteLiteral("</span><button class=\"btn delete right remove-region\"></button></li>\r\n");


            
            #line 139 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <div class=\"input\">\r\n                <input id=\"po" +
"_name\" type=\"text\" placeholder=\"");


            
            #line 142 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                        Write(Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n            <button id=\"po_add\" class=\"btn right\">");


            
            #line 143 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                             Write(Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n");


            
            #line 148 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
   Html.EndForm(); 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
