#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Template
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
    using Piranha.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Template/PostList.cshtml")]
    public class PostList : System.Web.Mvc.WebViewPage<Models.Manager.TemplateModels.PostListModel>
    {
        public PostList()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
  
    ViewBag.Title = Template.ListTitlePost;
    ViewBag.Selected = "Settings";
    ViewBag.SelectedTab = "PostType";



            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(function() {\r\n  " +
"          $(\".delete\").click(function() {\r\n                return confirm(\"");


            
            #line 14 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                           Write(Template.MessageDeletePostConfirm);

            
            #line default
            #line hidden
WriteLiteral(@""");
            });

            // Setup template list
            var options = {
                listClass: 'list-js',
                searchId: 'search',
                valueNames: ['name', 'updated', 'created']
            };
            var list = new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n    ");


            
            #line 28 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a href=\"");


            
            #line 32 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                        Write(Url.Action("post"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 32 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                         Write(Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"\" class=\"refresh\">");


            
            #line 33 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                          Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <button class=\"search\" title=\"");


            
            #line 35 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                     Write(Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 35 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                                     Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n   " +
"         <tr>\r\n                <th><span class=\"sort asc\" data-sort=\"name\">");


            
            #line 44 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                       Write(Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 45 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                                   Write(Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 46 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                                   Write(Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 51 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
             foreach (PostTemplate pt in Model.Templates)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td class=\"name\"><a href=\"");


            
            #line 54 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                         Write(Url.Action("post", new { id = pt.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 54 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                                                  Write(pt.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                    <td class=\"updated\">");


            
            #line 55 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                   Write(pt.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"created\">");


            
            #line 56 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                   Write(pt.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"buttons\">\r\n                        <a class" +
"=\"icon delete\" href=\"");


            
            #line 58 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
                                                Write(Url.Action("deletepost", new { id = pt.Id }));

            
            #line default
            #line hidden
WriteLiteral("\"></a></td>\r\n                </tr>\r\n");


            
            #line 60 "..\..\Areas\Manager\Views\Template\PostList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td colspan=" +
"\"5\"></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
