#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Template
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
    using Piranha.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Template/PostEdit.cshtml")]
    public class PostEdit : System.Web.Mvc.WebViewPage<Models.Manager.TemplateModels.PostEditModel>
    {
        public PostEdit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
  
    ViewBag.Selected = "Settings";
    ViewBag.SelectedTab = "PostType";



            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                   Write(Url.Content("~/Areas/Manager/Content/Js/jquery.template.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n    ");


            
            #line 12 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"toolbar\">\r\n        <div class=\"inner\">\r\n            <ul>\r\n     " +
"           <li><a class=\"save submit\">");


            
            #line 16 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                      Write(Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                        Write(Url.Action("deletepost", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 17 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                                                  Write(Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                        Write(Url.Action("postlist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 18 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                              Write(Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"");


            
            #line 19 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                        Write(Url.Action("post", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 19 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                                             Write(Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <div class=\"clear\"></div>\r\n        </di" +
"v>\r\n    </div>\r\n");


});

WriteLiteral("\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
   Html.BeginForm("post", "template"); 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 27 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 28 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 29 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 30 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 31 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 32 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div class=\"grid_9\">\r\n    <div class=\"box expandable\">\r\n        <div cl" +
"ass=\"title\"><h2>");


            
            #line 36 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 40 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 42 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 43 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 46 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 48 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Description, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n            <ul class=\"form opt" +
"ional\">               \r\n                <li>");


            
            #line 52 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Preview));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 54 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Preview, new { @rows = 8 }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>                \r\n            </ul>\r\n        </div>\r" +
"\n    </div>\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 60 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Global.Advanced);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 63 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Controller));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"right\">\r\n                        ");


            
            #line 65 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.CheckBoxFor(m => m.Template.ShowController));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"input short\">\r\n                        ");


            
            #line 67 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Controller, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>");


            
            #line 69 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.ArchiveController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"right\">\r\n                        ");


            
            #line 71 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.CheckBoxFor(m => m.Template.ShowArchiveController));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div class=\"input short\">\r\n                        ");


            
            #line 73 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.ArchiveController, new { @placeholder = Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 76 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.AllowRss));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p>");


            
            #line 77 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.AllowRss));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 77 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                               Write(Template.AllowRssDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</di" +
"v>\r\n<div class=\"grid_3\">\r\n");


            
            #line 84 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
     if (!Model.Template.IsNew && !string.IsNullOrEmpty(Model.Template.Preview.ToHtmlString()))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"box pagetemplate\">\r\n            <div class=\"title\"><h2>");


            
            #line 87 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                              Write(Resources.Page.HtmlPreview);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <div class=\"edit\">\r" +
"\n                    ");


            
            #line 90 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n");


            
            #line 94 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 96 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div id=\"region_data\"></div" +
">\r\n            <ul id=\"properties\" class=\"list buttons\">\r\n");


            
            #line 100 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                 foreach (string property in Model.Template.Properties)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><span>");


            
            #line 102 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                         Write(property);

            
            #line default
            #line hidden
WriteLiteral("</span><button class=\"btn delete right remove-region\"></button></li>\r\n");


            
            #line 103 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <div class=\"input\">\r\n                <input id=\"po" +
"_name\" type=\"text\" placeholder=\"");


            
            #line 106 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                        Write(Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n            <button id=\"po_add\" class=\"btn right\">");


            
            #line 107 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                             Write(Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n");


            
            #line 112 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
   Html.EndForm(); 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
